# -*- coding: utf-8 -*-
"""география_Сафиуллин.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vjVMshmMOkVIlWNXQnuNQU3_lJ83CbtB
"""

!pip install requests pandas

import requests
import pandas as pd

import pandas as pd
import folium
from folium.plugins import HeatMap
from google.colab import files
import time

API_KEY = '' # зарегался на "2гис: менеджер платформы" и создал api-ключ

# 1. ищем id Москвы
region_url = "https://catalog.api.2gis.com/2.0/region/search"
region_params = {'q': 'Москва', 'key': API_KEY}
region_response = requests.get(region_url, params=region_params)
region_response.raise_for_status() # проверка на ошибки
region_data = region_response.json() # json --> словарь
print(region_data)
moscow_id = None
if region_data.get('result') and region_data['result'].get('items'):
    moscow_id = region_data['result']['items'][0]['id']
    print(f"id Москвы: {moscow_id}")
else:
    print("не нашли id Москвы")

# 2. ищем автосалоны в Москве (5 страниц по 10 записей)
search_url = "https://catalog.api.2gis.com/3.0/items"

all_items = [] # резы

# цикл для 5 страниц
for current_page in range(1, 6):
    print(f"Загружаю страницу {current_page}...")

    search_params = {
        'q': 'автосалон',
        'region_id': moscow_id,
        'key': API_KEY,
        'fields': 'items.point,items.address_name',
        'page_size': 10,    # по 10 записей на стр.
        'page': current_page
    }

    search_response = requests.get(search_url, params=search_params)
    search_response.raise_for_status() # проверка на ошибки
    search_data = search_response.json() # json --> словарь
    print(search_data['result']['items'][0])

    # берём данные со страницы
    items = search_data.get('result', {}).get('items', []) # если не нашли, то пустой словарь/список
    if not items:
        print(f"На странице {current_page} данные закончились, прерываю загрузку.")
        break

    all_items.extend(items)  # .extend в отличие от .append распакует список перед добавлением
    print(f"Найдено {len(items)} салонов. Всего на сейчас: {len(all_items)}")

    time.sleep(0.3)  # пауза между запросами

print(f"\nВсего загружено объектов: {len(all_items)}")

# 3. обработка данных + табличка
print(all_items[0])
salons = []
for item in all_items:
    name = item.get('name')
    address = item.get('address_name')
    point = item.get('point')

    if point and isinstance(point, dict):  # проверяем: point непустой словарь
        lat = point.get('lat')
        lon = point.get('lon')
    else:
        lat, lon = None, None

    salons.append({'Название': name, 'Адрес': address, 'Широта': lat, 'Долгота': lon})

df = pd.DataFrame(salons)
print(f"Создана таблица из {len(df)} записей")
print("\nПервые 5 строк:")
print(df.head())

# 4. карта

df_clean = df.dropna(subset=['Широта', 'Долгота']).copy()
print(f"Записей с координатами: {len(df_clean)}")

if not df_clean.empty:
    center_lat = df_clean['Широта'].mean()
    center_lon = df_clean['Долгота'].mean()

    m = folium.Map(location=[center_lat, center_lon], zoom_start=11) # центр карты (location) + масштаб (zoom_start)

    for _, row in df_clean.iterrows(): # .iterrows() возвращает пары (индекс, строка) для каждой строки df
        folium.Marker(
            location=[row['Широта'], row['Долгота']],
            popup=f"{row['Название']}<br>{row['Адрес']}",
            icon=folium.Icon(color='red', icon='car', prefix='fa')
        ).add_to(m)

    heat_data = [[row['Широта'], row['Долгота']] for _, row in df_clean.iterrows()]
    HeatMap(heat_data, radius=12, blur=10).add_to(m)

    map_file = 'autosalon_map_50.html'
    m.save(map_file)
    files.download(map_file)
    print(f"\nКарта '{map_file}' сохранена и скачана. Откройте её.")
else:
    print("Нет данных для построения карты.")

print('Из карты видим, что меньше всего автосалонов в Восточном и Северо-Восточном административных округах. --> Открываем наш салон в одном из этих округов.')